# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /code/easy_kvstore

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /code/easy_kvstore

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /code/easy_kvstore/CMakeFiles /code/easy_kvstore/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /code/easy_kvstore/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named muduo_base

# Build rule for target.
muduo_base: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 muduo_base
.PHONY : muduo_base

# fast build rule for target.
muduo_base/fast:
	$(MAKE) -f muduo/base/CMakeFiles/muduo_base.dir/build.make muduo/base/CMakeFiles/muduo_base.dir/build
.PHONY : muduo_base/fast

#=============================================================================
# Target rules for targets named muduo_net

# Build rule for target.
muduo_net: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 muduo_net
.PHONY : muduo_net

# fast build rule for target.
muduo_net/fast:
	$(MAKE) -f muduo/net/CMakeFiles/muduo_net.dir/build.make muduo/net/CMakeFiles/muduo_net.dir/build
.PHONY : muduo_net/fast

#=============================================================================
# Target rules for targets named muduo_http

# Build rule for target.
muduo_http: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 muduo_http
.PHONY : muduo_http

# fast build rule for target.
muduo_http/fast:
	$(MAKE) -f muduo/net/http/CMakeFiles/muduo_http.dir/build.make muduo/net/http/CMakeFiles/muduo_http.dir/build
.PHONY : muduo_http/fast

#=============================================================================
# Target rules for targets named muduo_inspect

# Build rule for target.
muduo_inspect: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 muduo_inspect
.PHONY : muduo_inspect

# fast build rule for target.
muduo_inspect/fast:
	$(MAKE) -f muduo/net/inspect/CMakeFiles/muduo_inspect.dir/build.make muduo/net/inspect/CMakeFiles/muduo_inspect.dir/build
.PHONY : muduo_inspect/fast

#=============================================================================
# Target rules for targets named muduo_protobuf_codec

# Build rule for target.
muduo_protobuf_codec: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 muduo_protobuf_codec
.PHONY : muduo_protobuf_codec

# fast build rule for target.
muduo_protobuf_codec/fast:
	$(MAKE) -f muduo/net/protobuf/CMakeFiles/muduo_protobuf_codec.dir/build.make muduo/net/protobuf/CMakeFiles/muduo_protobuf_codec.dir/build
.PHONY : muduo_protobuf_codec/fast

#=============================================================================
# Target rules for targets named muduo_protorpc

# Build rule for target.
muduo_protorpc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 muduo_protorpc
.PHONY : muduo_protorpc

# fast build rule for target.
muduo_protorpc/fast:
	$(MAKE) -f muduo/net/protorpc/CMakeFiles/muduo_protorpc.dir/build.make muduo/net/protorpc/CMakeFiles/muduo_protorpc.dir/build
.PHONY : muduo_protorpc/fast

#=============================================================================
# Target rules for targets named muduo_protorpc_wire

# Build rule for target.
muduo_protorpc_wire: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 muduo_protorpc_wire
.PHONY : muduo_protorpc_wire

# fast build rule for target.
muduo_protorpc_wire/fast:
	$(MAKE) -f muduo/net/protorpc/CMakeFiles/muduo_protorpc_wire.dir/build.make muduo/net/protorpc/CMakeFiles/muduo_protorpc_wire.dir/build
.PHONY : muduo_protorpc_wire/fast

#=============================================================================
# Target rules for targets named easy_kvstore

# Build rule for target.
easy_kvstore: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 easy_kvstore
.PHONY : easy_kvstore

# fast build rule for target.
easy_kvstore/fast:
	$(MAKE) -f server/CMakeFiles/easy_kvstore.dir/build.make server/CMakeFiles/easy_kvstore.dir/build
.PHONY : easy_kvstore/fast

#=============================================================================
# Target rules for targets named kvstore_client

# Build rule for target.
kvstore_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kvstore_client
.PHONY : kvstore_client

# fast build rule for target.
kvstore_client/fast:
	$(MAKE) -f client/CMakeFiles/kvstore_client.dir/build.make client/CMakeFiles/kvstore_client.dir/build
.PHONY : kvstore_client/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... muduo_base"
	@echo "... muduo_net"
	@echo "... muduo_http"
	@echo "... muduo_inspect"
	@echo "... muduo_protobuf_codec"
	@echo "... muduo_protorpc"
	@echo "... muduo_protorpc_wire"
	@echo "... easy_kvstore"
	@echo "... kvstore_client"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

